version: '3.7'
services:
  career-forger-nlp-api-local:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    dns:
      - 100.64.0.1 #/etc/resolv.conf
      - ${IP_ADDRESS}
    container_name: career-forger-nlp-api-dev-local
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/.config/gcloud/application_default_credentials.json
      - PORT=8000
      - PYTHONPATH=/home/appuser/src:/home/appuser/tests
      - ENABLE_DOCS=true
      - IS_TEST_ENV=True
      - NLP_BUCKET=dummy_bucket
    ports:
      - "8003:8000"
    volumes:
      - ./src:/home/appuser/src
      - ./tests:/home/appuser/tests
      - ~/.config/gcloud/application_default_credentials.json:/home/appuser/.config/gcloud/application_default_credentials.json