apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
  labels:
    classification: prod
    cloud.googleapis.com/location: LOCATION
    run.googleapis.com/satisfiesPzs: 'true'
  name: gcp-cloud-run-template-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '3'
        run.googleapis.com/vpc-access-connector: serverless-conn-ew2
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: 70
      containers:
          image: LOCATION-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY_PATH:TAG
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240
      serviceAccountName: gcp-template-poc-cloud-run-user@PROJECT-NAME.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100